import pandas as pd
import sys
import os

def show_head(file_path, n=10):
    if not os.path.exists(file_path):
        print(f"❌ Error: File not found: {file_path}")
        print("   (Did you run the simulation step first?)")
        return

    try:
        df = pd.read_csv(file_path)
        print(f"\n📊 DATASET PREVIEW: {file_path}")
        print(f"   Total Samples: {len(df)}")
        print(f"   Columns: {list(df.columns)}")
        print("-" * 80)
        
        # Select key columns for display to avoid clutter
        cols_to_show = ['utc_ts', 'speed', 'acc_y', 'gyro_z', 'lat', 'lon']
        # Check if columns exist
        available_cols = [c for c in cols_to_show if c in df.columns]
        
        print(df[available_cols].head(n).to_string(index=False))
        print("-" * 80)
        print("... (more rows) ...\n")
        
    except Exception as e:
        print(f"Error reading file: {e}")

if __name__ == "__main__":
    # Default to the file generated by simulate.py in the guide
    csv_file = "data/live_test.csv"
    if len(sys.argv) > 1:
        csv_file = sys.argv[1]
    
    show_head(csv_file)
